using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace AXCODE
{
    [TestClass]
    public class AxSetup
    {
        [TestMethod]
        public void RunSetupTest()

        {


//			CREATE TABLE "MASTERTABLES_TBL"(
//	"MASTERTABLES_ID"   INTEGER PRIMARY KEY AUTOINCREMENT,
//	"MASTERTABLES_NAME" TEXT NOT NULL,
//	"ALIAS" TEXT NOT NULL,
//	"NAMESPACES_ID" INTEGER NOT NULL,
//	"DATABASES_ID"  INTEGER NOT NULL,
//	"ACTIVE_ID" INTEGER NOT NULL
//);


			//			CREATE TABLE "MASTERTABLES_TBL"(
			//	"MTABLES_ID"    INTEGER PRIMARY KEY AUTOINCREMENT,
			//	"MTABLES_NAME"  TEXT NOT NULL,
			//	"ALIAS" TEXT NOT NULL,
			//	"NAMESPACES_ID" INTEGER NOT NULL,
			//	"DATABASES_ID"  INTEGER NOT NULL,
			//	"ACTIVE_ID" INTEGER NOT NULL
			//);


			//			CREATE TABLE "MASTERTABLES_ITEMS_TBL"(
			//	"MTABLESITEMS_ID"   INTEGER PRIMARY KEY AUTOINCREMENT,
			//	"MTABLES_ID"    INTEGER NOT NULL,
			//	"FIELDSNAME"    TEXT NOT NULL,
			//	"DISPLAYNAME"   TEXT NOT NULL,
			//	"DATATYPE"  TEXT NOT NULL,
			//	"INPUTTYPE" TEXT NOT NULL,
			//	"WIDTH" TEXT NOT NULL,
			//	"HEIGHT"    TEXT NOT NULL,
			//	"CPOSITION" TEXT NOT NULL,
			//	"RPOSITION" TEXT NOT NULL,
			//	"ALIGNTO"   TEXT NOT NULL,
			//	"VALIDATE"  TEXT NOT NULL,
			//	"ISDEFAULT" TEXT NOT NULL,
			//	"PLACEMENT" TEXT NOT NULL
			//);


			//			CREATE TABLE "MASTERPATH_TBL"(
			//	"MPATH_ID"  INTEGER PRIMARY KEY AUTOINCREMENT,
			//	"MTABLES_ID"    INTEGER NOT NULL,
			//	"ROOT_FOLDER"   TEXT,
			//	"CONTFOLDER"    TEXT NOT NULL,
			//	"CLASSFOLDER"   TEXT NOT NULL,
			//	"FORMFOLDER"    TEXT NOT NULL,
			//	"LISTFOLDER"    TEXT NOT NULL,
			//	"SETUPFOLDER"   TEXT NOT NULL,
			//	"TESTFOLDER"    TEXT NOT NULL,
			//	"ACTIVE_ID" INTEGER NOT NULL
			//);


		}
    }
}
